#!/bin/bash

if [ $ETHERNET_AVAILABLE == "true" ]; then
    IFACE=$ETHERNET_IFACE
else
    IFACE=$WIFI_IFACE
fi

if [ $(ifconfig $IFACE | grep -c "inet addr:") -ge 1 ]; then
       exit 0
    else
       exit 1
fi


